// ---------------------------------------------------------------------------
// DATA, PART 2: deeper supplements, recovery/foundations, safety metadata
// ---------------------------------------------------------------------------

S.push(
  { id: "caffeine", name: "Caffeine", cat: "other", aka: ["Coffee", "Caffeine anhydrous"],
    sum: "The world's most used stimulant. Blocks the 'tired' signal (adenosine), which indirectly boosts dopamine and norepinephrine.",
    dose: [50, 200, "mg", "Morning, before ~2 pm", "A cup of coffee is roughly 80–120 mg. Stay under 400 mg a day total from all sources."],
    onset: [15, 45, null], dur: [3, 6, "Half-life is about 5 hours, so half of a 2 pm dose is still active at 7 pm."],
    tol: ["moderate", "Daily use makes your brain grow extra adenosine receptors, so you need caffeine to feel normal. Skipping it causes withdrawal headaches."],
    fx: ["Alertness and less fatigue", "Faster reaction time", "Better endurance", "Boosts dopamine signaling indirectly"],
    se: ["Jitters and anxiety", "Insomnia", "Raised heart rate and blood pressure", "Stomach upset", "Withdrawal headaches"],
    ix: [["L-Theanine", "beneficial", "Smooths out jitters and anxiety while keeping the focus.", "l-theanine"],
         ["Yohimbine", "moderate", "Heart rate and blood pressure effects stack.", "yohimbine"],
         ["Bitter Orange (Synephrine)", "moderate", "Combination linked to heart rhythm problems in case reports.", "synephrine"],
         ["Fluvoxamine, ciprofloxacin", "moderate", "These drugs slow caffeine clearance a lot; effects last much longer."],
         ["Anxiety or panic disorder", "moderate", "Can trigger anxiety and panic attacks."]],
    mech: "Blocks adenosine A1 and A2A receptors. In the striatum, A2A receptors are paired with dopamine D2 receptors, so blocking adenosine strengthens dopamine signaling. It also increases norepinephrine and adrenaline release.",
    bio: "Nearly 100% absorbed.",
    met: "Liver enzyme CYP1A2 breaks it down, mostly into paraxanthine. Genetics, birth control pills, and pregnancy slow it down; smoking speeds it up.",
    sol: ["water", null] },

  { id: "pea", name: "PEA (Phenethylamine)", cat: "other", aka: ["Phenylethylamine", "β-Phenylethylamine"],
    sum: "The 'chocolate' trace amine. A short, sharp burst of mood and energy, gone in minutes unless paired with Hordenine.",
    dose: [100, 500, "mg", "Occasional, morning", null],
    onset: [5, 15, null], dur: [0.25, 1, "Destroyed by MAO-B within minutes when taken alone."],
    tol: ["high", "Tolerance builds within days of daily use."],
    fx: ["Short burst of mood and energy", "Focus and motivation"],
    se: ["Anxiety", "Headache", "Rapid heartbeat", "Blood pressure spike", "Crash afterward"],
    ix: [["MAOIs", "major", "MAO is the only thing keeping PEA short. Blocking it can cause dangerous blood pressure spikes."],
         ["Hordenine", "moderate", "Stacked on purpose to make PEA last longer, but that also raises blood pressure risk.", "hordenine"],
         ["Other stimulants", "moderate", "Stacks heart rate and blood pressure effects."]],
    mech: "Activates TAAR1 receptors and causes nerve cells to release dopamine and norepinephrine.",
    bio: "Most oral PEA is destroyed by MAO-B in the gut and liver before reaching the brain.",
    met: "MAO-B converts it to phenylacetic acid.",
    sol: ["water", null] },

  { id: "hordenine", name: "Hordenine", cat: "other", aka: ["Barley extract"],
    sum: "A barley compound used almost only to make PEA last longer by slowing the enzyme that breaks it down.",
    dose: [25, 100, "mg", "With PEA", null],
    onset: [20, 40, null], dur: [1, 3, null], tol: ["low", "Little data."],
    fx: ["Extends PEA's effects", "Mild stimulation"],
    se: ["Rapid heartbeat", "Blood pressure increase", "Anxiety"],
    ix: [["MAOIs", "major", "Stacks MAO inhibition."],
         ["PEA", "moderate", "The intended pairing; also raises blood pressure risk.", "pea"],
         ["Mucuna pruriens", "moderate", "Slower dopamine breakdown plus extra L-DOPA can push blood pressure up.", "mucuna-pruriens"]],
    mech: "Competes for MAO-B, the enzyme that destroys PEA. Lab studies also show weak activation of dopamine D2 receptors.",
    bio: "Little human data.", met: "Little human data.",
    sol: ["water", null] },

  { id: "uridine", name: "Uridine (UMP)", cat: "other", aka: ["Uridine monophosphate"],
    sum: "A building block for synapse membranes. Paired with choline and DHA, it's the backbone of the 'synapse-building' stack.",
    dose: [250, 500, "mg", "Once daily", null],
    onset: [null, null, "Builds over weeks."], dur: [null, null, null], tol: ["none", null],
    fx: ["Supports building new synapse membranes (with choline and DHA)", "Mood support (limited evidence)", "Animal studies suggest it supports dopamine receptor sensitivity"],
    se: ["Rare: headache, stomach upset"],
    ix: [["Alpha-GPC / Citicoline", "beneficial", "Choline is the other half of the membrane-building reaction.", "alpha-gpc"]],
    mech: "Becomes CTP, which combines with choline to make CDP-choline and then phosphatidylcholine, the main membrane fat in synapses (the Kennedy pathway).",
    bio: "Moderate oral absorption.",
    met: "Broken down in the liver.",
    sol: ["water", null] },

  { id: "yohimbine", name: "Yohimbine", cat: "herbal", aka: ["Yohimbine HCl", "Yohimbe"],
    sum: "A strong norepinephrine booster from African tree bark. Used for fasted fat loss and energy. Easy to overdo.",
    dose: [2.5, 10, "mg", "Morning, fasted", "Start at 2.5 mg to test your reaction. Use yohimbine HCl; yohimbe bark products are often mislabeled."],
    onset: [15, 30, null], dur: [2, 4, null],
    tol: ["low", null],
    fx: ["Alertness", "Fat mobilization when fasted", "Used for erectile dysfunction"],
    se: ["Anxiety and panic attacks", "Racing heart", "Raised blood pressure", "Sweating, chills", "Nausea", "Insomnia"],
    ix: [["Anxiety or panic disorder", "major", "Can trigger panic attacks."],
         ["Blood pressure or heart conditions", "major", "Raises heart rate and blood pressure."],
         ["MAOIs and antidepressants", "major", "Stacks norepinephrine effects."],
         ["Caffeine", "moderate", "Effects stack.", "caffeine"]],
    mech: "Blocks alpha-2 receptors, the 'brakes' that tell nerves to stop releasing norepinephrine. Result: more norepinephrine.",
    bio: "Varies widely between people. Food and insulin blunt its fat-loss effect.",
    met: "Broken down in the liver (CYP2D6).",
    sol: ["water", null] },

  { id: "theacrine", name: "Theacrine", cat: "other", aka: ["TeaCrine"],
    sum: "Caffeine's cousin from a Chinese tea plant. Similar lift, but studies show little tolerance over weeks.",
    dose: [50, 200, "mg", "Morning", null],
    onset: [30, 60, null], dur: [4, 8, null],
    tol: ["low", "8-week studies showed no tolerance buildup."],
    fx: ["Energy and motivation", "Mood", "Focus"],
    se: ["Jitters", "Insomnia if taken late"],
    ix: [["Caffeine", "minor", "Common stack. Caffeine raises theacrine levels in the blood.", "caffeine"],
         ["Other stimulants", "moderate", "Stacks stimulation."]],
    mech: "Blocks adenosine receptors like caffeine. Animal studies also show dopamine receptor activity.",
    bio: "Limited data.", met: "Limited data; longer-lasting than caffeine.",
    sol: ["water", null] },

  { id: "synephrine", name: "Bitter Orange (Synephrine)", cat: "herbal", aka: ["p-Synephrine", "Citrus aurantium"],
    sum: "A fat-burner ingredient that mimics adrenaline at certain receptors. Mild alone; rougher on the heart with caffeine.",
    dose: [10, 50, "mg synephrine", "Morning", null],
    onset: [30, 60, null], dur: [2, 4, null], tol: ["low", null],
    fx: ["Small increase in calorie burn", "Mild energy"],
    se: ["Raised heart rate and blood pressure", "Headache", "Anxiety"],
    ix: [["Heart conditions or high blood pressure", "major", "Avoid."],
         ["MAOIs", "major", "Blocks its breakdown."],
         ["Caffeine", "moderate", "Combination linked to heart rhythm problems in case reports.", "caffeine"]],
    mech: "Activates adrenergic receptors, mainly beta-3 (fat burning), with weak alpha-1 activity.",
    bio: "Limited data.", met: "Broken down by MAO.",
    sol: ["water", null] },

  { id: "saffron", name: "Saffron", cat: "herbal", aka: ["Crocus sativus", "affron", "Satiereal"],
    sum: "The spice, as a standardized extract. Several trials found it helps mild depression about as well as low-dose antidepressants.",
    dose: [28, 30, "mg extract", "Daily, with food", "Studies mostly used 28–30 mg of standardized extract. Large amounts of saffron (5 g+) are toxic."],
    onset: [null, null, "Mood effects build over 4–8 weeks."], dur: [null, null, null], tol: ["none", null],
    fx: ["Mood support", "Less anxiety", "PMS symptom relief"],
    se: ["Dry mouth", "Nausea", "Headache"],
    ix: [["SSRIs and other serotonin drugs", "moderate", "Stacks serotonin effects."],
         ["Blood thinners", "minor", "May slightly increase bleeding risk."]],
    mech: "Crocin and safranal modestly block serotonin reuptake and reduce inflammation.",
    bio: "Crocin is converted to crocetin in the gut, which is absorbed.",
    met: "Limited data.", sol: ["water", null] },

  { id: "st-johns-wort", name: "St. John's Wort", cat: "herbal", aka: ["Hypericum perforatum"],
    sum: "A real herbal antidepressant with real drug interactions. It makes birth control and many medications less effective.",
    dose: [300, 300, "mg", "Three times daily (900 mg a day)", "Standardized to 0.3% hypericin."],
    onset: [null, null, "Effects build over 2–6 weeks."], dur: [null, null, null], tol: ["none", null],
    fx: ["Mild to moderate depression relief (good evidence)"],
    se: ["Sun sensitivity", "Stomach upset", "Fatigue", "Dizziness"],
    ix: [["Birth control, blood thinners, HIV drugs, transplant drugs", "major", "Speeds up liver enzymes (CYP3A4) and makes these drugs much less effective."],
         ["SSRIs, SNRIs, MAOIs, triptans", "major", "Risk of serotonin syndrome."],
         ["5-HTP", "major", "Stacks serotonin effects.", "5-htp"],
         ["L-Tryptophan", "major", "Stacks serotonin effects.", "l-tryptophan"],
         ["SAMe", "moderate", "Stacks serotonin effects.", "sam-e"]],
    mech: "Hyperforin blocks the reuptake of serotonin, norepinephrine, and dopamine, a broad effect similar to some antidepressants.",
    bio: "Hyperforin is absorbed and lasts about 9 hours.",
    met: "Liver; strongly speeds up CYP3A4 and P-glycoprotein, which clear many drugs.",
    sol: ["both", null] },

  { id: "sam-e", name: "SAMe", cat: "amino_acid_derivative", aka: ["S-Adenosyl methionine"],
    sum: "The body's universal methyl donor, needed to make and break down neurotransmitters. Decent evidence for mood and joint pain.",
    dose: [400, 1600, "mg", "Morning, empty stomach", "Buy enteric-coated tablets in blister packs; SAMe breaks down easily."],
    onset: [null, null, "Effects build over 1–2 weeks."], dur: [null, null, null], tol: ["none", null],
    fx: ["Mood support", "Osteoarthritis pain relief", "Liver support"],
    se: ["Stomach upset", "Anxiety or restlessness", "Insomnia", "Can trigger mania in bipolar disorder"],
    ix: [["SSRIs, SNRIs, MAOIs", "major", "Serotonin syndrome has been reported."],
         ["Bipolar disorder", "major", "Can trigger mania."],
         ["Levodopa", "minor", "SAMe is used up breaking down L-DOPA."]],
    mech: "Donates methyl groups for making serotonin, dopamine, and norepinephrine, and for COMT breaking them down. Also supports membrane fluidity.",
    bio: "Low; enteric coating protects it from stomach acid.",
    met: "Becomes SAH, then homocysteine, which B12, folate, and B6 recycle.",
    sol: ["water", null] },

  { id: "inositol", name: "Inositol", cat: "other", aka: ["Myo-inositol"],
    sum: "A sugar-like molecule that helps serotonin receptors pass their message into the cell. High doses studied for panic.",
    dose: [2000, 12000, "mg", "Split doses", "General use 2–4 g. Panic and OCD studies used 12–18 g a day."],
    onset: [null, null, "Builds over weeks."], dur: [null, null, null], tol: ["none", null],
    fx: ["Less anxiety and panic (small trials)", "Insulin sensitivity in PCOS"],
    se: ["Gas and stomach upset at high doses"],
    ix: [["Lithium", "minor", "Lithium works partly by lowering inositol; they may counteract."]],
    mech: "Part of the second-messenger system (phosphatidylinositol) used by serotonin 5-HT2 receptors and others.",
    bio: "Well absorbed.", met: "Cleared by the kidneys.",
    sol: ["water", "Sweet powder that dissolves easily."] },

  { id: "kava", name: "Kava", cat: "herbal", aka: ["Piper methysticum", "Kavalactones"],
    sum: "A Pacific Island root with fast, strong anxiety relief through GABA receptors. Rare liver injury risk; never with alcohol.",
    dose: [70, 250, "mg kavalactones", "Evening or as needed", "Use noble-cultivar root products only. Liver problems are linked to poor-quality material and stems or leaves."],
    onset: [20, 40, null], dur: [2, 4, null],
    tol: ["low", "Avoid heavy daily use; take regular breaks."],
    fx: ["Fast anxiety relief", "Relaxation and sociability", "Mostly clear-headed at moderate doses"],
    se: ["Drowsiness", "Stomach upset", "Dry, scaly skin with heavy use", "Rare serious liver injury"],
    ix: [["Alcohol", "major", "Liver risk and heavy sedation."],
         ["Benzodiazepines and sleep medications", "major", "Stacks sedation."],
         ["Acetaminophen and other liver-stressing drugs", "moderate", "Adds liver strain."],
         ["Levodopa", "moderate", "May reduce its effect."]],
    mech: "Kavalactones boost GABA-A receptors (at a different site than benzodiazepines), block sodium and calcium channels, and weakly inhibit MAO-B.",
    bio: "Kavalactones are fat-soluble and absorb better with fat.",
    met: "Liver; inhibits several CYP enzymes.",
    sol: ["fat", null] },

  { id: "taurine", name: "Taurine", cat: "amino_acid", aka: [],
    sum: "A mild, very safe calming amino acid, and the reason it's in energy drinks: it softens the jitters.",
    dose: [500, 3000, "mg", "Any time", null],
    onset: [30, 60, null], dur: [2, 4, null], tol: ["none", null],
    fx: ["Mild calming", "Heart and muscle support", "Softens stimulant jitters"],
    se: ["Rare: stomach upset"],
    ix: [["Lithium", "minor", "May slow lithium clearance."],
         ["Blood pressure medication", "minor", "May lower blood pressure slightly."]],
    mech: "Lightly activates GABA-A and glycine receptors and helps regulate calcium in cells.",
    bio: "Well absorbed.", met: "Cleared by the kidneys; also used to make bile salts.",
    sol: ["water", null] },

  { id: "apigenin", name: "Apigenin", cat: "herbal", aka: ["Chamomile extract"],
    sum: "The calming compound in chamomile tea. Popular as a gentle sleep aid.",
    dose: [50, 50, "mg", "30–60 minutes before bed", null],
    onset: [30, 60, null], dur: [3, 6, null], tol: ["low", null],
    fx: ["Easier time falling asleep", "Mild calming"],
    se: ["Drowsiness"],
    ix: [["Sedatives and sleep medications", "moderate", "Stacks sedation."],
         ["Blood thinners", "minor", "May slightly increase bleeding risk."]],
    mech: "Binds weakly to the benzodiazepine site on GABA-A receptors.",
    bio: "Poorly water-soluble; better with a fatty snack.",
    met: "Processed in the gut and liver.",
    sol: ["fat", null] },

  { id: "lemon-balm", name: "Lemon Balm", cat: "herbal", aka: ["Melissa officinalis"],
    sum: "A gentle mint-family herb that slows GABA breakdown. Calm without much sedation at low doses.",
    dose: [300, 600, "mg extract", "Afternoon or evening", null],
    onset: [60, 120, null], dur: [3, 5, null], tol: ["low", null],
    fx: ["Calm and better mood", "Mild sleep aid", "Small cognitive benefits in some studies"],
    se: ["Drowsiness", "Stomach upset"],
    ix: [["Sedatives", "moderate", "Stacks sedation."],
         ["Thyroid medication", "moderate", "May reduce thyroid hormone activity."]],
    mech: "Rosmarinic acid inhibits GABA transaminase, the enzyme that breaks down GABA.",
    bio: "Limited data.", met: "Limited data.",
    sol: ["water", null] },

  { id: "magnolia-bark", name: "Magnolia Bark", cat: "herbal", aka: ["Honokiol", "Magnolol", "Relora"],
    sum: "An Asian tree bark whose compounds boost GABA receptors. Used for sleep and stress.",
    dose: [200, 400, "mg extract", "Evening", null],
    onset: [30, 60, null], dur: [4, 6, null], tol: ["low", null],
    fx: ["Better sleep", "Less stress", "May lower cortisol"],
    se: ["Drowsiness", "Heartburn"],
    ix: [["Sedatives and sleep medications", "moderate", "Stacks sedation."],
         ["Blood thinners", "minor", "Honokiol has mild anti-clotting effects."]],
    mech: "Honokiol and magnolol boost GABA-A receptors and act on cannabinoid CB2 receptors.",
    bio: "Fat-soluble.", met: "Limited data.",
    sol: ["fat", null] },

  { id: "valerian", name: "Valerian", cat: "herbal", aka: ["Valeriana officinalis"],
    sum: "An old-school sleep herb. Evidence is mixed, and it smells like old socks.",
    dose: [300, 600, "mg extract", "30–120 minutes before bed", "Works more reliably after 2–4 weeks of nightly use."],
    onset: [30, 120, null], dur: [4, 8, null], tol: ["low", null],
    fx: ["Easier time falling asleep (mixed evidence)"],
    se: ["Morning grogginess", "Headache", "Vivid dreams", "Occasionally makes people more alert"],
    ix: [["Alcohol, sedatives, sleep medications", "moderate", "Stacks sedation."]],
    mech: "Valerenic acid boosts GABA-A receptors and slows GABA breakdown.",
    bio: "Limited data.", met: "Liver.",
    sol: ["both", null] },

  { id: "glycine", name: "Glycine", cat: "amino_acid", aka: [],
    sum: "A sweet-tasting amino acid that's also a calming neurotransmitter. 3 g before bed improves sleep quality in studies.",
    dose: [3000, 3000, "mg", "Before bed", null],
    onset: [30, 60, null], dur: [3, 6, null], tol: ["none", null],
    fx: ["Better sleep quality", "Lowers core body temperature at night", "Collagen building block"],
    se: ["Rare: stomach upset"],
    ix: [["Clozapine", "moderate", "May reduce its effect."]],
    mech: "An inhibitory neurotransmitter in the brainstem and spinal cord, and a required co-activator of glutamate's NMDA receptor.",
    bio: "Well absorbed.", met: "Used throughout the body.",
    sol: ["water", "Dissolves easily and tastes sweet."] },

  { id: "agmatine", name: "Agmatine", cat: "amino_acid_derivative", aka: ["Agmatine sulfate"],
    sum: "A compound made from arginine that blocks NMDA receptors. Studied for nerve pain and mood.",
    dose: [500, 1500, "mg", "Once or twice daily", null],
    onset: [30, 60, null], dur: [4, 6, null], tol: ["low", null],
    fx: ["Nerve pain relief (small trials)", "Mood support (limited)", "Animal studies show it slows tolerance to some drugs"],
    se: ["Nausea and stomach upset at high doses"],
    ix: [["Blood pressure medication", "minor", "May lower blood pressure."],
         ["Yohimbine", "minor", "Acts on the same alpha-2 receptors in opposite directions.", "yohimbine"]],
    mech: "Blocks NMDA receptors, binds imidazoline and alpha-2 receptors, and inhibits nitric oxide production.",
    bio: "Limited data.", met: "Broken down by agmatinase and diamine oxidase.",
    sol: ["water", null] },

  { id: "zinc", name: "Zinc", cat: "mineral", aka: ["Zinc picolinate", "Zinc glycinate"],
    sum: "A mineral released alongside glutamate that keeps NMDA receptors in check. Low zinc is linked to low mood.",
    dose: [15, 30, "mg elemental", "With food", "Upper limit is 40 mg a day. Long-term use drains copper."],
    onset: [null, null, "Works by keeping your levels topped up."], dur: [null, null, null], tol: ["none", null],
    fx: ["Immune support", "Mood support when low", "Testosterone support when low", "Taste and smell"],
    se: ["Nausea on an empty stomach", "Copper deficiency with long-term high doses"],
    ix: [["Copper", "moderate", "Zinc blocks copper absorption.", "copper"],
         ["Iron", "moderate", "Compete for absorption; separate by 2 hours.", "iron"],
         ["Tetracycline and quinolone antibiotics", "moderate", "Blocks absorption; separate by 2–4 hours."]],
    mech: "Stored with glutamate in some nerve terminals and released with it, where it inhibits NMDA receptors. Also needed by hundreds of enzymes.",
    bio: "Picolinate and glycinate absorb better than oxide. Phytates in grains and beans reduce absorption.",
    met: "Mostly cleared through the gut.",
    sol: ["water", null] },

  { id: "alcar", name: "Acetyl-L-Carnitine", cat: "amino_acid_derivative", aka: ["ALCAR", "ALC"],
    sum: "Fuels brain cell mitochondria and donates the acetyl half of acetylcholine. Clean mental energy for many people.",
    dose: [500, 2000, "mg", "Morning, empty stomach", null],
    onset: [30, 60, null], dur: [3, 5, null], tol: ["low", null],
    fx: ["Mental energy", "Less mental fatigue", "Nerve health (studied for neuropathy)", "Mood support in older adults"],
    se: ["Stomach upset", "Restlessness", "Fishy body odor", "Insomnia if taken late"],
    ix: [["Thyroid medication", "moderate", "May reduce thyroid hormone activity."],
         ["Warfarin", "moderate", "May increase its effect."]],
    mech: "Shuttles fatty acids into mitochondria for energy and donates its acetyl group toward acetyl-CoA, the other half of acetylcholine. Crosses into the brain better than plain L-carnitine.",
    bio: "Low oral bioavailability, but enough reaches the brain to matter.",
    met: "Split into carnitine and acetate; cleared by the kidneys.",
    sol: ["water", null] },

  { id: "dmae", name: "DMAE", cat: "choline_source", aka: ["Dimethylaminoethanol", "Deanol"],
    sum: "Sold as an acetylcholine booster for decades. The evidence that it actually raises brain acetylcholine is weak.",
    dose: [100, 300, "mg", "Morning", null],
    onset: [30, 60, null], dur: [3, 5, null], tol: ["low", null],
    fx: ["Mild alertness and mood (weak evidence)"],
    se: ["Headache", "Muscle tension", "Insomnia"],
    ix: [["Pregnancy", "major", "Linked to birth defects in animal studies. Avoid."],
         ["Anticholinergic drugs", "moderate", "Opposite effects."],
         ["Alzheimer's drugs (donepezil and similar)", "moderate", "May stack cholinergic effects."]],
    mech: "Originally thought to become choline in the brain. Newer evidence suggests it competes with choline for transport and may not raise acetylcholine at all.",
    bio: "Crosses the blood-brain barrier.", met: "Limited data.",
    sol: ["water", null] },

  { id: "choline-bitartrate", name: "Choline Bitartrate", cat: "choline_source", aka: ["Choline"],
    sum: "Cheap, basic choline. Fine for covering your diet, but it gets into the brain less well than Alpha-GPC or Citicoline.",
    dose: [500, 1000, "mg", "With a meal", "About 41% choline by weight. Most adults need 425–550 mg of choline a day from all sources."],
    onset: [null, null, "Mostly fills dietary gaps."], dur: [null, null, null], tol: ["none", null],
    fx: ["Covers dietary choline needs", "Liver health"],
    se: ["Fishy body odor", "Stomach upset", "Sweating at high doses"],
    ix: [["Anticholinergic drugs", "minor", "Opposite effects."]],
    mech: "Supplies choline, which is used for acetylcholine, cell membranes, and methylation.",
    bio: "Absorbed well, but much is used by the liver or turned into TMA by gut bacteria before reaching the brain.",
    met: "Liver; gut bacteria convert some to TMA, then TMAO.",
    sol: ["water", null] },

  { id: "phosphatidylserine", name: "Phosphatidylserine", cat: "other", aka: ["PS", "Sunflower PS"],
    sum: "A membrane fat concentrated in brain cells. Supports memory in older adults and blunts the cortisol stress response.",
    dose: [100, 300, "mg", "With a meal", "Cortisol studies used 400–800 mg around workouts."],
    onset: [null, null, "Builds over weeks."], dur: [null, null, null], tol: ["none", null],
    fx: ["Memory support in older adults", "Lower cortisol response to stress", "Attention support (small studies, with omega-3)"],
    se: ["Insomnia or stomach upset above 300 mg"],
    ix: [["Blood thinners", "minor", "May slightly increase effect."],
         ["Anticholinergic drugs", "minor", "May work against them."]],
    mech: "Makes up part of the inner layer of nerve cell membranes, where it helps receptors and signaling proteins work. Also dampens the HPA stress axis.",
    bio: "Absorbed; made from soy or sunflower lecithin.",
    met: "Partly converted to other phospholipids.",
    sol: ["fat", null] },

  { id: "omega-3", name: "Omega-3 (EPA/DHA)", cat: "other", aka: ["Fish oil", "Algae oil"],
    sum: "DHA is a main structural fat in your brain; EPA helps mood. One of the best-supported foundations for brain health.",
    dose: [1000, 2000, "mg EPA+DHA", "With your largest meal", "Count EPA + DHA on the label, not total fish oil. For mood, studies favor EPA-heavy formulas around 1 g EPA."],
    onset: [null, null, "Brain and blood levels build over 8–12 weeks."], dur: [null, null, null], tol: ["none", null],
    fx: ["Mood support (EPA)", "Brain cell membrane structure (DHA)", "Lower inflammation", "Heart health"],
    se: ["Fishy burps", "Stomach upset", "Bleeding risk at very high doses"],
    ix: [["Blood thinners", "moderate", "Adds to bleeding risk at higher doses."],
         ["Blood pressure medication", "minor", "May lower blood pressure slightly."]],
    mech: "DHA keeps neuron membranes flexible so receptors (including dopamine and serotonin receptors) work properly. EPA lowers inflammation, which affects mood.",
    bio: "Triglyceride form absorbs better than ethyl ester. Take with a meal that has fat.",
    met: "Built into cell membranes or burned for energy.",
    sol: ["fat", null] },

  { id: "vitamin-d3", name: "Vitamin D3", cat: "vitamin", aka: ["Cholecalciferol"],
    sum: "A hormone more than a vitamin. It switches on the gene for making brain serotonin, and low levels are linked to low mood.",
    dose: [1000, 4000, "IU", "With your largest meal", "Upper limit is 4,000 IU a day without testing. Get a blood test (25-OH vitamin D) to dose properly."],
    onset: [null, null, "Blood levels build over 6–12 weeks."], dur: [null, null, null], tol: ["none", null],
    fx: ["Mood support when low", "Bone health", "Immune support"],
    se: ["Too much calcium with long-term high doses (nausea, kidney stones)"],
    ix: [["Thiazide diuretics", "moderate", "Risk of high blood calcium."],
         ["Vitamin K2", "beneficial", "K2 sends the extra calcium to bones instead of arteries.", "vitamin-k2"]],
    mech: "Acts through vitamin D receptors in the brain and switches on tryptophan hydroxylase 2, the enzyme that makes brain serotonin.",
    bio: "Fat-soluble; absorbs best with a meal containing fat.",
    met: "Converted to 25-OH vitamin D in the liver, then to the active form (calcitriol) in the kidneys. Both steps need magnesium.",
    sol: ["fat", null] },

  { id: "vitamin-k2", name: "Vitamin K2 (MK-7)", cat: "vitamin", aka: ["Menaquinone-7"],
    sum: "D3's partner. It directs calcium into bones and keeps it out of arteries.",
    dose: [100, 200, "mcg", "With D3 and a meal", null],
    onset: [null, null, "Works over weeks."], dur: [null, null, null], tol: ["none", null],
    fx: ["Directs calcium into bones", "Artery health", "Helps the brain make sphingolipids (limited data)"],
    se: ["Rare"],
    ix: [["Warfarin", "major", "Vitamin K directly counteracts warfarin. Do not take without a doctor."]],
    mech: "Activates proteins (osteocalcin and matrix Gla protein) that bind calcium and put it in the right place.",
    bio: "MK-7 is fat-soluble and stays in the blood for about 3 days.",
    met: "Liver.",
    sol: ["fat", null] },

  { id: "vitamin-b12", name: "Vitamin B12", cat: "vitamin", aka: ["Methylcobalamin", "Cyanocobalamin"],
    sum: "Needed for nerve insulation (myelin) and for the methylation that makes neurotransmitters. Low B12 causes fatigue and brain fog.",
    dose: [500, 1000, "mcg", "Once daily", "Vegans, older adults, and people on metformin or acid reducers are commonly low."],
    onset: [null, null, "Works by keeping your levels topped up."], dur: [null, null, null], tol: ["none", null],
    fx: ["Energy and mental clarity when low", "Nerve health", "Methylation (with folate)"],
    se: ["Rare: acne"],
    ix: [["Metformin, acid reducers (PPIs)", "moderate", "These drugs lower B12. Supplementing helps."]],
    mech: "Works with methylfolate in methionine synthase to recycle homocysteine into methionine and then SAMe.",
    bio: "Normal absorption needs stomach intrinsic factor. High oral doses still work because about 1% absorbs passively.",
    met: "Stored in the liver for years.",
    sol: ["water", null] },

  { id: "creatine", name: "Creatine", cat: "amino_acid_derivative", aka: ["Creatine monohydrate"],
    sum: "The best-studied sports supplement also fuels the brain. Helps thinking under sleep deprivation, especially for vegetarians.",
    dose: [3000, 5000, "mg", "Daily, any time", "Monohydrate is the proven form. Takes weeks to saturate, or 5–7 days with a 20 g/day loading phase."],
    onset: [null, null, "Builds over 2–4 weeks."], dur: [null, null, null], tol: ["none", null],
    fx: ["Brain energy reserve", "Thinking under sleep deprivation", "Muscle strength and power"],
    se: ["Water weight", "Stomach upset with large single doses", "Raises creatinine on blood tests (not kidney damage)"],
    ix: [["Kidney disease", "moderate", "Check with a doctor."],
         ["NSAIDs and other kidney-stressing drugs", "minor", "Theoretical added kidney load."]],
    mech: "Stored as phosphocreatine, which quickly recharges ATP, the cell's energy currency, in brain and muscle.",
    bio: "Nearly complete absorption.",
    met: "Converted to creatinine and cleared by the kidneys.",
    sol: ["water", "Not very soluble; stir well or mix into a shake."] },

  { id: "lions-mane", name: "Lion's Mane", cat: "herbal", aka: ["Hericium erinaceus"],
    sum: "A mushroom that stimulates nerve growth factor in lab studies. Early human trials look promising for memory and mood.",
    dose: [500, 3000, "mg", "Daily", "Choose fruiting-body extracts with listed beta-glucans over mycelium on grain."],
    onset: [null, null, "Builds over weeks."], dur: [null, null, null], tol: ["none", null],
    fx: ["Nerve growth factor support (lab and animal studies)", "Memory in mild cognitive impairment (small trials)", "Mood and anxiety (small trials)"],
    se: ["Stomach upset", "Rare skin rash", "Mushroom allergy"],
    ix: [["Blood thinners", "minor", "May slightly increase bleeding risk."],
         ["Diabetes medication", "minor", "May lower blood sugar."]],
    mech: "Hericenones (fruiting body) and erinacines (mycelium) stimulate nerve growth factor (NGF) production in lab studies.",
    bio: "Limited data.", met: "Limited data.",
    sol: ["both", "Dual (hot water + alcohol) extracts capture both types of compounds."] }
);

MAP.push(
  ["caffeine", "dopamine", "modulator", "moderate", "Blocks adenosine, which takes the brakes off dopamine signaling. Doesn't add dopamine."],
  ["caffeine", "norepinephrine", "modulator", "moderate", "Raises norepinephrine and adrenaline release."],
  ["pea", "dopamine", "releaser", "limited", "Releases dopamine directly, but oral PEA is destroyed within minutes."],
  ["pea", "norepinephrine", "releaser", "limited", "Releases norepinephrine too, which is where the heart-rate bump comes from."],
  ["hordenine", "dopamine", "enzyme_inhibitor", "limited", "Slows the breakdown of PEA, which is why it's stacked with it."],
  ["uridine", "dopamine", "modulator", "limited", "Animal studies suggest it supports dopamine release and receptor sensitivity."],
  ["uridine", "acetylcholine", "modulator", "limited", "Combines with choline to build the membranes synapses are made of."],
  ["theacrine", "dopamine", "modulator", "limited", "Caffeine's cousin. Similar adenosine effect, with less tolerance in studies."],
  ["yohimbine", "norepinephrine", "receptor_antagonist", "moderate", "Blocks the receptor that tells nerves to stop releasing norepinephrine. Strong, and easy to overdo."],
  ["synephrine", "norepinephrine", "receptor_agonist", "limited", "Mimics adrenaline at fat-burning receptors. Mild alone, harder on the heart with caffeine."],
  ["saffron", "serotonin", "reuptake_inhibitor", "moderate", "Several trials found it helps mild depression about as well as low-dose antidepressants."],
  ["st-johns-wort", "serotonin", "reuptake_inhibitor", "strong", "A real antidepressant effect, and real drug interactions."],
  ["sam-e", "serotonin", "modulator", "moderate", "The body's methyl donor, needed to make and break down neurotransmitters. Decent mood evidence."],
  ["sam-e", "dopamine", "modulator", "limited", "Supports dopamine turnover; also used to clear it."],
  ["inositol", "serotonin", "modulator", "limited", "Helps serotonin receptors pass their signal into the cell. High doses studied for panic."],
  ["omega-3", "serotonin", "modulator", "limited", "EPA-heavy fish oil helps mood in studies; DHA keeps receptor membranes flexible."],
  ["omega-3", "dopamine", "modulator", "limited", "Low DHA reduces dopamine receptor function in animal studies."],
  ["vitamin-d3", "serotonin", "modulator", "limited", "Switches on the gene for brain serotonin production. Low vitamin D is linked to low mood."],
  ["kava", "gaba", "modulator", "moderate", "Strong, fast anxiety relief through GABA receptors. Liver concerns; never with alcohol."],
  ["taurine", "gaba", "receptor_agonist", "limited", "Lightly activates GABA and glycine receptors. Mild and very safe."],
  ["apigenin", "gaba", "modulator", "limited", "The calming compound in chamomile. Popular as a sleep aid."],
  ["lemon-balm", "gaba", "enzyme_inhibitor", "limited", "Slows the enzyme that breaks down GABA. Gentle and calming."],
  ["magnolia-bark", "gaba", "modulator", "limited", "Honokiol and magnolol boost GABA receptors. Popular for sleep and stress."],
  ["valerian", "gaba", "modulator", "limited", "Old-school sleep herb. Evidence is mixed."],
  ["glycine", "gaba", "modulator", "limited", "Its own calming neurotransmitter, working alongside GABA. 3 g before bed improves sleep quality."],
  ["glycine", "glutamate", "modulator", "limited", "A required co-activator of glutamate's NMDA receptor."],
  ["agmatine", "glutamate", "receptor_antagonist", "limited", "Blocks NMDA receptors. Studied for nerve pain and mood."],
  ["zinc", "glutamate", "modulator", "moderate", "Released alongside glutamate and dampens NMDA receptors. Low zinc is linked to low mood."],
  ["alcar", "acetylcholine", "precursor", "limited", "Donates the acetyl half of acetylcholine and fuels brain cell mitochondria."],
  ["dmae", "acetylcholine", "precursor", "theoretical", "Sold as an acetylcholine booster, but the evidence it raises brain acetylcholine is weak."],
  ["choline-bitartrate", "acetylcholine", "precursor", "limited", "Cheap choline. Fine for diet gaps, but reaches the brain less well than Alpha-GPC or Citicoline."],
  ["phosphatidylserine", "acetylcholine", "modulator", "limited", "Increases acetylcholine release in animal studies; a key membrane building block."]
);

Object.assign(COF, {
  "caffeine": { items: [["l-theanine", "Smooths jitters and anxiety. Use about 2 parts theanine to 1 part caffeine.", "Together"]] },
  "pea": { items: [["hordenine", "Slows PEA breakdown so it lasts more than a few minutes. Also raises blood pressure risk.", "Together"]], note: "Not a cofactor relationship; this is the usual pairing." },
  "hordenine": { items: [["pea", "Hordenine is mainly used to extend PEA.", "Together"]] },
  "uridine": { items: [
    ["alpha-gpc", "Choline is the other half of the membrane-building reaction.", "Together"],
    ["omega-3", "DHA completes the 'uridine + choline + DHA' combination studied for building synapses.", "With a meal"]],
    note: "These aren't cofactors but the known synergy stack." },
  "yohimbine": { items: [], note: "No cofactors. Take it fasted; food and insulin blunt it. Start at 2.5 mg." },
  "theacrine": { items: [], note: "No cofactors. Often stacked with a small dose of caffeine." },
  "synephrine": { items: [], note: "No cofactors. Avoid pairing with caffeine if you have any heart concerns." },
  "saffron": { items: [], note: "No cofactors. Take with food." },
  "st-johns-wort": { items: [], note: "No cofactors. Check every medication you take before starting it." },
  "sam-e": { items: [
    ["vitamin-b12", "Recycles the homocysteine SAMe leaves behind.", "Any time, daily"],
    ["l-methylfolate", "Works with B12 in that recycling step.", "Any time, daily"],
    ["vitamin-b6", "Clears homocysteine by a second route.", "Together"]] },
  "inositol": { items: [], note: "No cofactors. High doses are easier to tolerate split through the day." },
  "kava": { items: [], note: "No cofactors. Never with alcohol." },
  "taurine": { items: [], note: "No cofactors. Pairs well with caffeine to soften jitters." },
  "apigenin": { items: [["magnesium-glycinate", "A common evening pairing for sleep.", "Evening"]] },
  "lemon-balm": { items: [], note: "No cofactors." },
  "magnolia-bark": { items: [], note: "No cofactors. Evening only; it's sedating." },
  "valerian": { items: [], note: "No cofactors. Give it 2–4 weeks of nightly use before judging it." },
  "glycine": { items: [["magnesium-glycinate", "A common sleep pairing.", "Evening"]] },
  "agmatine": { items: [], note: "No cofactors." },
  "zinc": { items: [["copper", "Long-term zinc above about 25 mg drains copper. 1–2 mg of copper prevents it.", "Separate by 2 h"]] },
  "alcar": { items: [["alpha-gpc", "Choline + an acetyl group are the two halves of acetylcholine.", "Together"]] },
  "dmae": { items: [], note: "No cofactors. Alpha-GPC or Citicoline are better-supported choline sources." },
  "choline-bitartrate": { items: [["vitamin-b5", "Becomes acetyl-CoA, which joins choline to form acetylcholine.", "Together"]] },
  "phosphatidylserine": { items: [["omega-3", "PS + omega-3 combinations were studied for memory and attention.", "With a meal"]] },
  "omega-3": { items: [], note: "Take with your largest meal. Store in the fridge to slow it going rancid." },
  "vitamin-d3": { items: [
    ["vitamin-k2", "Sends the extra calcium D3 absorbs into bones instead of arteries.", "Together, with fat"],
    ["magnesium-glycinate", "Both steps that activate vitamin D need magnesium.", "Any time"]] },
  "vitamin-k2": { items: [["vitamin-d3", "The standard pairing. D3 raises calcium absorption; K2 directs it.", "Together, with fat"]] },
  "vitamin-b12": { items: [["l-methylfolate", "They work together in methylation.", "Together"]] },
  "l-methylfolate": { items: [["vitamin-b12", "High folate without B12 can hide a B12 deficiency, and the two work together in methylation.", "Together"]] },
  "creatine": { items: [], note: "No cofactors. Timing doesn't matter; taking it every day does." },
  "lions-mane": { items: [], note: "No cofactors." }
});

