const S = [
  { id: "l-tyrosine", name: "L-Tyrosine", cat: "amino_acid", aka: ["Tyrosine"],
    sum: "An amino acid your body turns into dopamine and norepinephrine. Best for staying sharp under stress or sleep loss.",
    dose: [500, 2000, "mg", "Once daily or before demanding tasks", "Studies on stress used about 100–150 mg per kg of body weight. Benefits mostly show up under stress, not on a normal day."],
    onset: [30, 60, "Blood levels peak about 1–2 hours after dosing."], dur: [2, 4, null],
    tol: ["low", "The pathway is self-regulating, so extra tyrosine helps mainly when you're burning through dopamine fast."],
    fx: ["Preserves working memory and mental flexibility under stress", "Alertness during sleep deprivation", "Supports thyroid hormone production"],
    se: ["Headache", "Nausea or heartburn", "Jitteriness at high doses"],
    ix: [["MAOIs", "major", "More catecholamines with the breakdown enzyme blocked. Risk of dangerous blood pressure spikes."],
         ["Thyroid medication (levothyroxine)", "moderate", "Tyrosine is a building block of thyroid hormone and may add to its effects."],
         ["Mucuna pruriens / levodopa", "moderate", "They compete for the same doorway into the brain (LAT1). Take at different times.", "mucuna-pruriens"]],
    mech: "Tyrosine hydroxylase (the rate-limiting step, needs BH4 and iron) turns it into L-DOPA. AADC (needs B6) turns L-DOPA into dopamine. Dopamine β-hydroxylase (needs vitamin C and copper) turns dopamine into norepinephrine.",
    bio: "Well absorbed. It enters the brain through LAT1, competing with other amino acids from protein, so take it on an empty stomach.",
    met: "Used for protein, catecholamines, and thyroid hormone. The excess is broken down in the liver.",
    sol: ["water", "Poorly soluble (about 0.45 g per liter), so it mixes badly into drinks. Capsules are easier."] },

  { id: "n-acetyl-l-tyrosine", name: "N-Acetyl L-Tyrosine", cat: "amino_acid_derivative", aka: ["NALT"],
    sum: "A modified tyrosine that dissolves easily but converts poorly. Marketed as better than L-Tyrosine; the data says otherwise.",
    dose: [300, 600, "mg", "Once daily", "Raises blood tyrosine less per gram than plain L-Tyrosine."],
    onset: [30, 60, null], dur: [2, 4, null], tol: ["low", "Same as L-Tyrosine."],
    fx: ["Same intended effects as L-Tyrosine, usually weaker"], se: ["Headache", "Nausea"],
    ix: [["MAOIs", "major", "Same as L-Tyrosine."], ["Thyroid medication (levothyroxine)", "moderate", "Same as L-Tyrosine."]],
    mech: "Has to be stripped of its acetyl group, mostly in the kidneys, to become L-Tyrosine before it can enter the dopamine pathway.",
    bio: "Poor. A large share of each dose is peed out unchanged.",
    met: "Converted to L-Tyrosine in the kidneys; the rest is excreted.",
    sol: ["water", "Much more soluble than L-Tyrosine, which is why it shows up in drinks and pre-workouts."] },

  { id: "dl-phenylalanine", name: "DL-Phenylalanine", cat: "amino_acid", aka: ["DLPA"],
    sum: "A 50/50 mix of two forms of phenylalanine. The L-form feeds the dopamine pathway; the D-form may help with pain and mood.",
    dose: [500, 1500, "mg", "Once or twice daily, mornings", "Avoid entirely if you have PKU."],
    onset: [30, 60, null], dur: [2, 4, null], tol: ["low", null],
    fx: ["Mood and motivation support", "Produces PEA, a short-acting natural stimulant", "D-form may slow the breakdown of the body's own painkillers (weak evidence)"],
    se: ["Anxiety or jitteriness", "Headache", "Raised blood pressure", "Insomnia if taken late"],
    ix: [["Phenylketonuria (PKU)", "major", "Do not take. People with PKU can't process phenylalanine."],
         ["MAOIs", "major", "Risk of blood pressure spikes. PEA is normally cleared by MAO."],
         ["Antipsychotics", "moderate", "Linked to worsening of tardive dyskinesia (involuntary movements)."],
         ["Mucuna pruriens / levodopa", "moderate", "Competes for LAT1 entry into the brain.", "mucuna-pruriens"]],
    mech: "Phenylalanine hydroxylase (needs BH4 and iron) turns L-phenylalanine into L-Tyrosine, which then follows the dopamine pathway. Some becomes phenethylamine (PEA). D-phenylalanine is thought to block enkephalinase, the enzyme that breaks down enkephalins.",
    bio: "The L-form absorbs well and competes with other amino acids for LAT1. The D-form absorbs less efficiently.",
    met: "L-form is converted to tyrosine in the liver. D-form is partly converted and partly excreted.",
    sol: ["water", "Moderately soluble (about 30 g per liter)."] },

  { id: "mucuna-pruriens", name: "Mucuna Pruriens", cat: "herbal", aka: ["Velvet bean", "Kapikachhu"],
    sum: "A tropical bean naturally loaded with L-DOPA, the direct precursor to dopamine. The strongest dopamine option here, with the most side effects.",
    dose: [200, 500, "mg extract", "Once daily; many people cycle it", "Dose by L-DOPA content, not extract weight. 500 mg of a 15% extract is about 75 mg of L-DOPA. Extracts range from 15% to 98%."],
    onset: [30, 60, "L-DOPA peaks in the blood within 30 minutes to 2 hours."], dur: [2, 4, "L-DOPA has a half-life of about 1–1.5 hours."],
    tol: ["high", "It skips the body's own speed limit on dopamine production. With regular use the system adapts and the effect fades, which is why people cycle it."],
    fx: ["Faster, stronger dopamine boost than amino acids", "Mood, motivation, and libido", "May raise growth hormone and lower prolactin"],
    se: ["Nausea and vomiting", "Lightheadedness when standing up", "Insomnia", "Involuntary movements at high doses", "Agitation or paranoia at high doses"],
    ix: [["MAOIs", "major", "Risk of a hypertensive crisis."],
         ["Parkinson's medication (carbidopa/levodopa)", "major", "Doubles up on L-DOPA. Don't combine without a doctor."],
         ["Antipsychotics", "moderate", "Works against the medication at dopamine receptors."],
         ["Iron", "moderate", "Iron binds L-DOPA and blocks absorption. Separate by at least 2 hours.", "iron"],
         ["High-dose vitamin B6", "moderate", "Converts L-DOPA to dopamine in the gut and blood, where it can't reach the brain.", "vitamin-b6"],
         ["5-HTP", "moderate", "Both rely on the same enzyme (AADC). A big dose of one can crowd out the other.", "5-htp"],
         ["L-Tyrosine / DL-Phenylalanine", "minor", "Compete for LAT1. Take at separate times.", "l-tyrosine"]],
    mech: "The seeds contain L-DOPA, which skips the rate-limiting tyrosine hydroxylase step. AADC (needs B6) converts it straight into dopamine.",
    bio: "Absorbed in the upper small intestine through amino acid transporters, so protein meals reduce it. Most is converted to dopamine outside the brain, which causes the nausea. Only a small fraction makes it in.",
    met: "AADC turns it into dopamine. COMT and MAO break dopamine down.",
    sol: ["water", "L-DOPA is only slightly soluble, a bit better in acidic liquids."] },

  { id: "l-tryptophan", name: "L-Tryptophan", cat: "amino_acid", aka: ["Tryptophan"],
    sum: "The amino acid behind serotonin and melatonin, famous from turkey dinners. Gentle, and mostly used for sleep.",
    dose: [500, 2000, "mg", "30–60 minutes before bed", "A contaminated batch in 1989 caused a serious illness (EMS). Modern supplies are clean, but buy reputable brands."],
    onset: [30, 60, null], dur: [3, 6, null], tol: ["low", null],
    fx: ["Easier time falling asleep", "Mild mood support", "May reduce carb cravings"],
    se: ["Drowsiness", "Nausea", "Heartburn"],
    ix: [["SSRIs, SNRIs, MAOIs, tramadol, triptans", "major", "Risk of serotonin syndrome."],
         ["5-HTP", "moderate", "Stacks serotonin effects; start low if combining.", "5-htp"],
         ["Sleep medications and sedatives", "minor", "Adds to drowsiness."]],
    mech: "Tryptophan hydroxylase (rate-limiting, needs BH4 and iron) turns it into 5-HTP. AADC (needs B6) turns 5-HTP into serotonin.",
    bio: "Absorbs well but competes with other amino acids for LAT1. Eating carbs helps because insulin pulls the competitors into muscle.",
    met: "Over 90% goes down the kynurenine pathway (toward niacin, needs B6) rather than becoming serotonin. Stress and inflammation push more that way.",
    sol: ["water", null] },

  { id: "5-htp", name: "5-HTP", cat: "amino_acid_derivative", aka: ["5-Hydroxytryptophan", "Griffonia simplicifolia"],
    sum: "The step right before serotonin, extracted from an African seed. Stronger and faster than tryptophan.",
    dose: [50, 300, "mg", "Split into 2–3 doses, or once in the evening", "Start at 50 mg. Nausea gets worse with dose."],
    onset: [30, 90, null], dur: [3, 6, "Half-life of roughly 2–7 hours."],
    tol: ["moderate", "Long-term use on its own is theorized to lower dopamine, since both compete for the same enzyme. Evidence is limited."],
    fx: ["Mood support", "Reduced appetite", "Sleep support via melatonin"],
    se: ["Nausea", "Diarrhea or stomach upset", "Drowsiness", "Vivid dreams"],
    ix: [["SSRIs, SNRIs, MAOIs, tramadol, triptans", "major", "Risk of serotonin syndrome."],
         ["St. John's Wort", "major", "Stacks serotonin effects."],
         ["Mucuna pruriens / L-DOPA", "moderate", "Compete for the same enzyme (AADC).", "mucuna-pruriens"]],
    mech: "Skips the rate-limiting tryptophan hydroxylase step. AADC (needs B6) converts it straight into serotonin.",
    bio: "About 70% absorbed. Crosses the blood-brain barrier easily and isn't slowed much by competing amino acids. A lot converts in the gut, which causes the nausea.",
    met: "Becomes serotonin, which MAO breaks down to 5-HIAA.",
    sol: ["water", null] },

  { id: "l-theanine", name: "L-Theanine", cat: "amino_acid", aka: ["Theanine", "Suntheanine"],
    sum: "The calming amino acid in green tea. Relaxed but alert, and it takes the edge off coffee.",
    dose: [100, 400, "mg", "As needed", "The classic stack is 200 mg theanine with 100 mg caffeine."],
    onset: [30, 60, "Peaks around 50 minutes."], dur: [2, 4, null], tol: ["low", null],
    fx: ["Calm focus without sleepiness", "More alpha brain waves (relaxed-alert state)", "Smooths out caffeine jitters", "May improve sleep quality"],
    se: ["Rare: mild headache or drowsiness"],
    ix: [["Caffeine", "beneficial", "Works together for focus and cuts caffeine anxiety."],
         ["Blood pressure medication", "minor", "May lower blood pressure slightly."]],
    mech: "Shaped like glutamate. It weakly blocks glutamate receptors, raises GABA, and may nudge dopamine and serotonin.",
    bio: "Well absorbed and crosses the blood-brain barrier through amino acid transporters.",
    met: "Broken down mainly in the kidneys into glutamate and ethylamine.",
    sol: ["water", "Dissolves easily in drinks."] },

  { id: "magnesium-glycinate", name: "Magnesium Glycinate", cat: "mineral", aka: ["Magnesium bisglycinate", "Magnesium"],
    sum: "Magnesium bound to glycine, the gentle, well-absorbed form. Calms the nervous system, and many people are low.",
    dose: [200, 400, "mg elemental", "Evening", "Upper limit from supplements is 350 mg a day; higher doses mainly cause loose stools. Check the label for elemental magnesium, not total compound weight."],
    onset: [null, null, "Mostly builds over days to weeks, though some people feel calmer the same evening."], dur: [null, null, null],
    tol: ["none", null],
    fx: ["Better sleep quality", "Muscle relaxation, fewer cramps", "Calmer stress response"],
    se: ["Loose stools (less with glycinate than citrate or oxide)", "Drowsiness"],
    ix: [["Kidney disease", "major", "Your kidneys clear magnesium. With poor kidney function it can build up to dangerous levels."],
         ["Tetracycline and quinolone antibiotics", "moderate", "Blocks antibiotic absorption. Separate by 2–4 hours."],
         ["Osteoporosis drugs (bisphosphonates)", "moderate", "Reduces their absorption. Separate by 2 hours."]],
    mech: "Sits inside glutamate's NMDA receptor like a plug, keeping it from overfiring. It also supports GABA signaling.",
    bio: "Glycinate and citrate absorb much better than oxide. Absorption goes down as dose goes up.",
    met: "Not broken down. Levels are controlled by the kidneys.",
    sol: ["water", null] },

  { id: "ashwagandha", name: "Ashwagandha", cat: "herbal", aka: ["Withania somnifera", "KSM-66", "Sensoril"],
    sum: "An Ayurvedic adaptogen root. Lowers stress and cortisol and has GABA-like calming effects.",
    dose: [300, 600, "mg extract", "Daily, with food", "Use a standardized root extract like KSM-66 or Sensoril. Avoid during pregnancy."],
    onset: [null, null, "Builds over 2–8 weeks of daily use."], dur: [null, null, null],
    tol: ["low", "Some people cycle it, though there's little evidence tolerance develops."],
    fx: ["Lower perceived stress and cortisol", "Better sleep", "Less anxiety", "May raise testosterone in men"],
    se: ["Stomach upset", "Drowsiness", "May raise thyroid hormone", "Rare cases of liver injury"],
    ix: [["Pregnancy", "major", "Avoid."],
         ["Thyroid medication", "moderate", "May raise thyroid hormone levels further."],
         ["Sedatives and benzodiazepines", "moderate", "Adds to sedation."],
         ["Immunosuppressants", "moderate", "May stimulate the immune system and work against them."]],
    mech: "Its active compounds (withanolides) act on GABA-A receptors and calm the body's stress hormone system (the HPA axis).",
    bio: "Depends heavily on the extract. Standardized extracts are what the studies used.",
    met: "Not well studied.",
    sol: ["both", "Contains both water- and fat-soluble compounds; take with a meal."] },

  { id: "l-glutamine", name: "L-Glutamine", cat: "amino_acid", aka: ["Glutamine"],
    sum: "The most common amino acid in your blood. Raw material for both glutamate and GABA, though it mostly feeds your gut.",
    dose: [2000, 5000, "mg", "Once or twice daily", null],
    onset: [null, null, "Not a fast-acting supplement."], dur: [null, null, null], tol: ["none", null],
    fx: ["Fuel for gut lining cells", "Raw material for glutamate and GABA", "May reduce sugar cravings (weak evidence)"],
    se: ["Bloating", "Generally well tolerated"],
    ix: [["Liver disease", "major", "Raises ammonia, which a damaged liver can't clear."],
         ["Seizure medications", "moderate", "Could in theory raise glutamate and work against them."]],
    mech: "Glutaminase turns it into glutamate inside nerve cells. Glutamate decarboxylase (needs B6) then turns some of that into GABA.",
    bio: "Gut cells use a large share before it reaches the bloodstream, and little gets into the brain.",
    met: "Used by the gut, liver, and kidneys as a nitrogen carrier and fuel.",
    sol: ["water", "Dissolves fine in water; flavorless powder."] },

  { id: "n-acetyl-cysteine", name: "NAC", cat: "amino_acid_derivative", aka: ["N-Acetyl Cysteine"],
    sum: "Builds glutathione, the body's main antioxidant, and rebalances glutamate. Studied for cravings and compulsive habits.",
    dose: [600, 1800, "mg", "Split into 2–3 doses", null],
    onset: [null, null, "Effects on mood and cravings build over 1–2 weeks."], dur: [null, null, null], tol: ["low", null],
    fx: ["Raises glutathione", "Rebalances glutamate", "Studied for cravings, addiction, and compulsive behaviors", "Thins mucus"],
    se: ["Nausea", "Stomach upset", "Sulfur smell", "Headache"],
    ix: [["Nitroglycerin", "moderate", "Can cause low blood pressure and severe headaches."],
         ["Activated charcoal", "minor", "Binds NAC and reduces absorption."]],
    mech: "Provides cysteine for glutathione. It also drives the cystine-glutamate exchanger, which releases a little glutamate outside the synapse. That signals nerve cells to release less glutamate into the synapse.",
    bio: "Low, around 6–10%. Much of it is processed by the liver first.",
    met: "Converted to cysteine in the liver, then used to make glutathione.",
    sol: ["water", null] },

  { id: "alpha-gpc", name: "Alpha-GPC", cat: "choline_source", aka: ["Choline alfoscerate"],
    sum: "A choline source that gets into the brain efficiently. The go-to for boosting acetylcholine.",
    dose: [300, 600, "mg", "Once or twice daily", "About 40% choline by weight. Studies on cognitive decline used 1,200 mg a day split into 3 doses."],
    onset: [30, 60, null], dur: [4, 6, null], tol: ["low", null],
    fx: ["Supports memory and focus", "May increase power output in athletes", "Supports brain cell membranes"],
    se: ["Headache", "Heartburn", "Dizziness", "Insomnia", "Low mood in some people"],
    ix: [["Anticholinergic drugs (diphenhydramine, scopolamine)", "moderate", "Opposite effects."],
         ["Alzheimer's drugs (donepezil and similar)", "moderate", "Stacks cholinergic effects: headache, stomach upset, cramping."],
         ["Huperzine A", "minor", "A common stack. Start low; side effects stack too.", "huperzine-a"]],
    mech: "Releases choline, which choline acetyltransferase joins with acetyl-CoA to make acetylcholine. The other half supports cell membranes.",
    bio: "Well absorbed and crosses the blood-brain barrier better than basic choline salts.",
    met: "Split into choline and glycerophosphate. Gut bacteria turn some choline into TMA, which the liver makes into TMAO. One observational study linked Alpha-GPC to higher stroke risk; that doesn't prove it caused it.",
    sol: ["water", "Absorbs moisture from the air, so the powder clumps."] },

  { id: "citicoline", name: "Citicoline", cat: "choline_source", aka: ["CDP-Choline", "Cognizin"],
    sum: "A choline source that also delivers uridine for building brain cell membranes. Gentler than Alpha-GPC, with some dopamine support.",
    dose: [250, 500, "mg", "Once or twice daily", "About 18% choline by weight. Studies used up to 2,000 mg a day."],
    onset: [60, 120, null], dur: [4, 6, null], tol: ["low", null],
    fx: ["Attention and focus", "Memory support, especially in older adults", "Supports brain cell membrane repair"],
    se: ["Headache", "Insomnia", "Stomach upset"],
    ix: [["Levodopa", "moderate", "May strengthen levodopa's effect."],
         ["Anticholinergic drugs", "moderate", "Opposite effects."],
         ["Huperzine A", "minor", "A common stack. Start low.", "huperzine-a"]],
    mech: "Splits into choline and cytidine. Choline feeds acetylcholine. Cytidine becomes uridine, which helps build phospholipid membranes. Animal studies show increased dopamine receptor density.",
    bio: "About 90% absorbed.",
    met: "Broken down in the gut wall and liver into choline and cytidine, which turns into uridine in humans.",
    sol: ["water", null] },

  { id: "huperzine-a", name: "Huperzine A", cat: "herbal", aka: ["Hup A", "Huperzia serrata"],
    sum: "A compound from Chinese club moss that slows the breakdown of acetylcholine. Potent at tiny doses and lasts a long time.",
    dose: [50, 200, "mcg", "Once daily; usually cycled", "Micrograms, not milligrams. A long half-life means it builds up with daily use."],
    onset: [30, 90, null], dur: [8, 14, "Half-life of roughly 10–14 hours."],
    tol: ["moderate", "Commonly cycled (for example a few days on, a few off) because it builds up and receptors may adapt. Mostly based on user experience."],
    fx: ["Better memory and recall", "Sharper focus", "Vivid dreams"],
    se: ["Nausea or diarrhea", "Sweating", "Muscle twitching", "Slowed heart rate", "Blurry vision"],
    ix: [["Alzheimer's drugs (donepezil and similar)", "major", "Same mechanism. Stacking can cause a cholinergic overload."],
         ["Beta-blockers and other heart-slowing drugs", "moderate", "Adds to a slowed heart rate."],
         ["Anticholinergic drugs", "moderate", "Opposite effects."],
         ["Alpha-GPC / Citicoline", "minor", "A common stack. Start low; side effects stack too.", "alpha-gpc"]],
    mech: "Reversibly blocks acetylcholinesterase (AChE), the enzyme that breaks down acetylcholine, so it lasts longer in the synapse. Also weakly blocks NMDA receptors.",
    bio: "Absorbs well and crosses the blood-brain barrier easily.",
    met: "Mostly cleared unchanged by the kidneys.",
    sol: ["both", "The dose is so small that food and solubility barely matter."] },

  { id: "bacopa", name: "Bacopa Monnieri", cat: "herbal", aka: ["Brahmi", "Water hyssop"],
    sum: "An Ayurvedic herb with some of the best evidence for memory. The catch: it takes 8–12 weeks of daily use to work.",
    dose: [300, 600, "mg extract", "Daily, with a meal", "Studies mostly used 300 mg of an extract standardized to about 50% bacosides."],
    onset: [null, null, "Memory benefits show up after 8–12 weeks of daily use."], dur: [null, null, null], tol: ["low", null],
    fx: ["Better memory retention", "Faster recall", "Less anxiety"],
    se: ["Nausea or stomach cramps", "Diarrhea", "Tiredness", "Dry mouth"],
    ix: [["Anticholinergic drugs", "moderate", "May work against them."],
         ["Alzheimer's drugs (donepezil and similar)", "moderate", "May stack cholinergic effects."],
         ["Thyroid medication", "minor", "Raised thyroid hormone in animal studies."],
         ["Sedatives", "minor", "May add to drowsiness."]],
    mech: "Its bacosides support repair of synapses, act as antioxidants, and in animal studies boost acetylcholine production while slowing its breakdown.",
    bio: "Bacosides are fat-soluble and absorb better with food that contains fat.",
    met: "Not well studied.",
    sol: ["fat", "Take with a meal that has some fat."] },

  { id: "rhodiola", name: "Rhodiola Rosea", cat: "herbal", aka: ["Golden root", "Arctic root"],
    sum: "A cold-climate adaptogen root for mental fatigue. Helps you hold up under stress rather than adding a buzz.",
    dose: [200, 600, "mg extract", "Morning, on an empty stomach", "Look for an extract standardized to about 3% rosavins and 1% salidroside."],
    onset: [30, 120, "Some effect within hours; also builds over weeks."], dur: [4, 6, null],
    tol: ["low", "Some people cycle it."],
    fx: ["Less mental fatigue under stress", "Better mental performance when tired", "Mild mood support"],
    se: ["Dizziness", "Dry mouth", "Jitteriness or insomnia if taken late", "Irritability"],
    ix: [["Antidepressants (especially MAOIs)", "moderate", "Weakly blocks MAO in lab studies; may stack effects."],
         ["Stimulants", "minor", "May add to stimulation."]],
    mech: "Its active compounds (salidroside, rosavins) calm the body's stress hormone system and weakly block MAO in lab studies. That may keep dopamine, norepinephrine, and serotonin from crashing during stress.",
    bio: "Limited human data.",
    met: "Limited human data.",
    sol: ["water", null] },

  { id: "vitamin-b6", name: "Vitamin B6 (P5P)", cat: "vitamin", aka: ["Pyridoxal 5'-phosphate", "Pyridoxine"],
    sum: "The cofactor that runs the final step for dopamine and serotonin, and the step that makes GABA.",
    dose: [10, 50, "mg", "Once daily", "You only need 1.3–1.7 mg a day from food. US upper limit is 100 mg; the EU set 12 mg in 2023. Long-term high doses can cause nerve damage (tingling or numbness); stop if that happens."],
    onset: [null, null, "Works by keeping your levels topped up over days to weeks."], dur: [null, null, null], tol: ["none", null],
    fx: ["Needed to make dopamine, serotonin, GABA, and histamine", "Supports amino acid metabolism"],
    se: ["Nausea", "Nerve damage with long-term high doses"],
    ix: [["Mucuna pruriens / levodopa without carbidopa", "moderate", "Converts L-DOPA before it reaches the brain.", "mucuna-pruriens"],
         ["Seizure medications (phenytoin, phenobarbital)", "moderate", "High doses may lower drug levels."]],
    mech: "P5P is the active coenzyme for AADC (L-DOPA to dopamine, 5-HTP to serotonin), glutamate decarboxylase (glutamate to GABA), and many other enzymes.",
    bio: "Well absorbed. Regular pyridoxine has to be converted to P5P in the liver; the P5P form skips that step.",
    met: "Converted to P5P in the liver and excreted in urine.",
    sol: ["water", null] },

  { id: "vitamin-c", name: "Vitamin C", cat: "vitamin", aka: ["Ascorbic acid"],
    sum: "Needed to turn dopamine into norepinephrine, and helps your body absorb iron.",
    dose: [250, 1000, "mg", "Split doses absorb better", "Upper limit is 2,000 mg a day."],
    onset: [null, null, "Works by keeping your levels topped up."], dur: [null, null, null], tol: ["none", null],
    fx: ["Turns dopamine into norepinephrine", "Antioxidant that keeps BH4 working", "Boosts iron absorption"],
    se: ["Diarrhea above about 2 g", "Kidney stone risk at high doses in some people"],
    ix: [["Iron", "beneficial", "Increases iron absorption.", "iron"],
         ["Aluminum antacids", "minor", "Increases aluminum absorption."]],
    mech: "Required by dopamine β-hydroxylase, the enzyme that makes norepinephrine. Also recycles BH4.",
    bio: "Absorption drops at high doses: 70–90% at normal amounts, under 50% above 1 g.",
    met: "Excess leaves in urine.",
    sol: ["water", null] },

  { id: "iron", name: "Iron", cat: "mineral", aka: ["Iron bisglycinate", "Ferrous sulfate"],
    sum: "Needed for the slowest step in making both dopamine and serotonin. Only supplement if a blood test shows you're low.",
    dose: [18, 45, "mg elemental", "Every other day absorbs better than daily", "Get ferritin tested first. RDA is 8 mg for men and 18 mg for premenopausal women; upper limit is 45 mg. Bisglycinate is easiest on the stomach."],
    onset: [null, null, "Restoring iron takes weeks to months."], dur: [null, null, null], tol: ["none", null],
    fx: ["Enables dopamine and serotonin production", "Low iron is linked to fatigue, low motivation, and restless legs"],
    se: ["Constipation", "Nausea", "Dark stools", "Iron overload if you're not actually low"],
    ix: [["Mucuna pruriens / levodopa", "moderate", "Binds L-DOPA and blocks absorption. Separate by 2+ hours.", "mucuna-pruriens"],
         ["Thyroid medication (levothyroxine)", "moderate", "Blocks absorption. Separate by 4 hours."],
         ["Tetracycline and quinolone antibiotics", "moderate", "Each blocks the other's absorption."],
         ["Calcium, coffee, tea", "minor", "Reduce iron absorption. Take apart."],
         ["Vitamin C", "beneficial", "Increases absorption.", "vitamin-c"]],
    mech: "Tyrosine hydroxylase, tryptophan hydroxylase, and phenylalanine hydroxylase all need iron. These are the rate-limiting steps for dopamine and serotonin.",
    bio: "Plant-type iron absorbs at only 2–20%. Better on an empty stomach and with vitamin C. Each dose raises hepcidin, a hormone that blocks absorption for about a day, which is why every other day works better.",
    met: "Your body has no way to get rid of extra iron, which is why overload is possible.",
    sol: ["water", null] },

  { id: "copper", name: "Copper", cat: "mineral", aka: ["Copper glycinate"],
    sum: "The second requirement (with vitamin C) for turning dopamine into norepinephrine. Most people get enough from food.",
    dose: [1, 2, "mg", "Once daily", "RDA is 0.9 mg; upper limit is 10 mg. Mainly worth taking if you're on long-term zinc."],
    onset: [null, null, "Works by keeping your levels topped up."], dur: [null, null, null], tol: ["none", null],
    fx: ["Turns dopamine into norepinephrine", "Needed for iron metabolism"],
    se: ["Nausea", "Liver damage from long-term excess"],
    ix: [["Wilson's disease", "major", "Do not take. The body can't clear copper."],
         ["High-dose zinc", "moderate", "Zinc blocks copper absorption."]],
    mech: "Dopamine β-hydroxylase is a copper enzyme.",
    bio: "Roughly 30–50% absorbed; the body adjusts absorption to need.",
    met: "Stored in the liver and cleared through bile.",
    sol: ["water", null] },

  { id: "l-methylfolate", name: "L-Methylfolate", cat: "vitamin", aka: ["5-MTHF", "Methylfolate", "Folate"],
    sum: "The active form of folate. Helps make BH4, a helper molecule the dopamine- and serotonin-making enzymes depend on.",
    dose: [400, 1000, "mcg", "Once daily", "Prescription doses for depression are 7.5–15 mg. Pair with vitamin B12."],
    onset: [null, null, "Works by keeping your levels topped up."], dur: [null, null, null], tol: ["none", null],
    fx: ["Supports BH4 for dopamine, serotonin, and norepinephrine", "Supports methylation (SAMe)"],
    se: ["Irritability or anxiety in some people", "Insomnia", "Can hide a B12 deficiency"],
    ix: [["Methotrexate", "major", "Can interfere with the drug. Needs a doctor."],
         ["Seizure medications (phenytoin and others)", "moderate", "May lower drug levels; the drugs also drain folate."]],
    mech: "Supports making and recycling BH4, which tyrosine and tryptophan hydroxylase need. Also donates methyl groups to make SAMe.",
    bio: "Already active, so it skips the MTHFR enzyme that regular folic acid needs. Matters for people with MTHFR gene variants.",
    met: "Hands its methyl group to homocysteine (with B12's help), making methionine and then SAMe.",
    sol: ["water", null] },

  { id: "vitamin-b5", name: "Vitamin B5", cat: "vitamin", aka: ["Pantothenic acid"],
    sum: "Your body uses it to make acetyl-CoA, the other half of the acetylcholine molecule.",
    dose: [50, 500, "mg", "Once daily", "You only need about 5 mg a day from food, and deficiency is rare."],
    onset: [null, null, "Works by keeping your levels topped up."], dur: [null, null, null], tol: ["none", null],
    fx: ["Supplies acetyl-CoA for acetylcholine", "Supports energy metabolism"],
    se: ["Diarrhea at very high doses"],
    ix: [["Biotin (high dose)", "minor", "They share an absorption transporter."]],
    mech: "Becomes coenzyme A, then acetyl-CoA. Choline acetyltransferase joins acetyl-CoA with choline to form acetylcholine.",
    bio: "Well absorbed through a transporter it shares with biotin.",
    met: "Excreted unchanged in urine.",
    sol: ["water", null] }
];

