"""Journey staging page (#journey): the two-capsule first screen and the tour chapters (Swallow, Stomach,
Small intestine, Different paths, Bloodstream, Blood-brain barrier, Synapse).
Usage: python3 tools/test_journey.py [base-url]      (default http://localhost:8010)
"""
import json, os, subprocess, sys, tempfile, time, urllib.request
HERE = os.path.dirname(os.path.abspath(__file__))
exec(open(os.path.join(HERE, "shoot.py")).read().replace('if __name__ == "__main__":', "if False:"))
BASE = sys.argv[1].rstrip("/") if len(sys.argv) > 1 else "http://localhost:8010"
prof = tempfile.mkdtemp()
proc = subprocess.Popen([CHROME, "--headless=new", f"--remote-debugging-port={PORT}", f"--user-data-dir={prof}", "--hide-scrollbars", "about:blank"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
fails = []
try:
    for _ in range(80):
        try: tabs = json.load(urllib.request.urlopen(f"http://127.0.0.1:{PORT}/json")); break
        except Exception: time.sleep(.5)
    c = CDP([t for t in tabs if t["type"] == "page"][0]["webSocketDebuggerUrl"])
    c.call("Page.enable"); c.call("Runtime.enable"); c.call("Network.enable"); c.call("Network.setCacheDisabled", cacheDisabled=True)
    def size(w, h, mobile=False): c.call("Emulation.setDeviceMetricsOverride", width=w, height=h, deviceScaleFactor=1, mobile=mobile)
    def ev(e):
        r = c.call("Runtime.evaluate", expression=e, awaitPromise=True, returnByValue=True)
        if "exceptionDetails" in r: print("  JS error:", r["exceptionDetails"].get("exception", {}).get("description", "")[:200])
        return r["result"].get("value")
    def check(name, ok, detail=""):
        print(f"  {'PASS' if ok else 'FAIL'}  {name}{(' (' + str(detail) + ')') if detail else ''}")
        if not ok: fails.append(name)
    def open_journey():
        c.call("Page.navigate", url=f"{BASE}/#journey"); time.sleep(1.5)
        ev("window.__e = []; addEventListener('error', e => __e.push(e.message))")

    size(1280, 800)
    print("First screen:")
    open_journey()
    check("two capsules, Start and Skip", ev("[...document.querySelectorAll('.jy-pill')].map(b => b.dataset.journey).join()") == "start,skip")
    check("labels come from content/journey.js", ev("document.querySelector('.jy-start .jy-label').textContent === JOURNEY.pills.start && document.querySelector('.jy-skip .jy-label').textContent === JOURNEY.pills.skip"))
    check("pills are real buttons with a spoken hint", ev("[...document.querySelectorAll('.jy-pill')].every(b => b.tagName === 'BUTTON' && document.getElementById(b.getAttribute('aria-describedby')))"))
    check("top bar and footer are hidden", ev("getComputedStyle(document.querySelector('.chrome')).display === 'none' && getComputedStyle(document.querySelector('footer')).display === 'none'"))
    check("background is black", ev("getComputedStyle(document.body).backgroundColor") == "rgb(0, 0, 0)")
    check("disclaimer is a visible line, not a gate", ev("(() => { const r = document.querySelector('.jy-note').getBoundingClientRect(); return r.height > 0 && r.bottom <= innerHeight })()"))
    check("pills side by side on desktop", ev("(() => { const [a, b] = [...document.querySelectorAll('.jy-pill')].map(x => x.getBoundingClientRect()); return Math.abs(a.top - b.top) < 20 && b.left > a.right })()"))

    print("Routing:")
    ev("document.querySelector('[data-journey=skip]').click()"); time.sleep(.5)
    check("Skip Journey opens the Stack builder", ev("location.hash") == "#stack" and ev("!!document.querySelector('.builder, #view .bstep, #view [class*=builder]')"))
    check("leaving restores the top bar", ev("getComputedStyle(document.querySelector('.chrome')).display") != "none" and not ev("document.body.classList.contains('is-journey')"))
    open_journey()
    ev("document.querySelector('[data-journey=note]').click()"); time.sleep(.8)
    check("Read more goes to the home page notice", ev("location.hash") in ("", "#") and ev("!!document.getElementById('notice')"))
    check("current Explore home page is unchanged", ev("!!document.querySelector('.tc') && document.querySelectorAll('#view > section').length") == 5)

    print("Start Journey (chapter 1, Swallow):")
    open_journey()
    ev("document.querySelector('[data-journey=start]').click()"); time.sleep(.3)
    check("Skip pill and note fade away", ev("getComputedStyle(document.querySelector('.jy-skip')).pointerEvents") == "none")
    time.sleep(2.2)
    centre = "(() => { const r = document.querySelector('.jy-actor').getBoundingClientRect(); return [Math.round(r.left + r.width / 2 - innerWidth / 2), Math.round(r.top + r.height / 2 - innerHeight / 2)] })()"
    check("pill flies to the centre of the screen", ev(centre) == [0, 0], ev(centre))
    check("pill shrinks on Start so the head can be in proportion", abs(float(ev("document.querySelector('.jy-actor').style.getPropertyValue('--zoom')")) - ev("jyPillStart() * JY.base")) < 0.01)
    check("pill loses its label (blank puppet)", ev("getComputedStyle(document.querySelector('.jy-actor .jy-label')).opacity") == "0")
    check("page now scrolls", ev("document.documentElement.scrollHeight > innerHeight * 3"))
    check("mouth is drawn, first caption shows", ev("getComputedStyle(document.querySelector('.jy-world')).opacity") == "1" and ev("document.querySelector('.jy-t').textContent") == ev("JOURNEY.swallow[0].title"))
    check("skip link and chapter dots are visible", ev("getComputedStyle(document.querySelector('.jy-hud')).visibility") == "visible" and ev("document.querySelectorAll('.jy-rail li').length") == ev("JOURNEY.chapters.length"))
    def at(key, q): ev(f"jyGoto('{key}', {q})"); time.sleep(.6)
    def titles(key, qs):
        out = []
        for q in qs: at(key, q); out.append(ev("document.querySelector('.jy-t').textContent"))
        return out
    caps = titles("swallow", (0.05, 0.4, 0.65, 0.95))
    check("chapter 1 captions change in order as you scroll", caps == ev("JOURNEY.swallow.map(c => c.title)"), caps)
    at("swallow", 0.6)
    check("pill stays centred while scrolling", ev(centre) == [0, 0], ev(centre))
    check("esophagus is drawn, mouth has faded", ev("+getComputedStyle(document.getElementById('jy-tube')).opacity") == 1 and ev("+getComputedStyle(document.getElementById('jy-mouth')).opacity") == 0)
    check("Esophagus label shows mid-way", ev("document.getElementById('jy-call').classList.contains('on')"))
    rot = lambda: float(ev("document.querySelector('.jy-actor').style.getPropertyValue('--rot')").replace("deg", ""))
    check("pill is back to full size in the esophagus", abs(float(ev("document.querySelector('.jy-actor').style.getPropertyValue('--zoom')")) - ev("JY.base")) < 0.01)
    check("pill has turned lengthwise", abs(rot() - ev("JOURNEY.swallowChoreo.tubeTilt")) < 0.01, rot())
    check("each drawing is its own small SVG", ev("[...document.querySelectorAll('.jy svg')].every(s => s.querySelectorAll('*').length < 300)"), ev("[...document.querySelectorAll('.jy svg')].map(s => s.querySelectorAll('*').length)"))

    print("Sources:")
    check("every caption's source ids exist in JOURNEY.cite", ev("Object.keys(JOURNEY).filter(k => Array.isArray(JOURNEY[k]) && JOURNEY[k][0] && JOURNEY[k][0].kicker).every(k => JOURNEY[k].every(c => (c.src || []).every(id => JOURNEY.cite[id] && JOURNEY.cite[id].url.startsWith('https://'))))"))
    at("swallow", 0.4)
    check("a science caption shows its source, faint, bottom-left, as a link", ev("document.querySelector('#jy-src a') && document.querySelector('#jy-src a').href") == ev("JOURNEY.cite.openstax.url") and ev("(() => { const r = document.getElementById('jy-src').getBoundingClientRect(); return r.left < innerWidth / 3 && r.bottom > innerHeight - 60 })()") and ev("parseFloat(getComputedStyle(document.getElementById('jy-src')).color.split(',')[3])") < 0.6)
    check("source links open in a new tab", ev("[...document.querySelectorAll('#jy-src a')].every(a => a.target === '_blank' && a.rel.includes('noopener'))"))
    at("swallow", 0.05)
    check("captions without science claims show no source line", ev("document.getElementById('jy-src').textContent") == "")

    print("Chapter 2, Stomach:")
    at("stomach", 0.3)
    check("stomach scene takes over; chapter 1 is hidden underneath", ev("getComputedStyle(document.getElementById('jy-ch-stomach')).visibility") == "visible" and ev("getComputedStyle(document.getElementById('jy-ch-swallow')).visibility") == "hidden")
    check("second chapter dot is current, first is done", ev("[...document.querySelectorAll('.jy-rail li')].map(l => l.hasAttribute('aria-current') ? 'now' : l.classList.contains('done') ? 'done' : '-').slice(0, 3).join()") == "done,now,-")
    check("fluid in front makes the pill look half-submerged", ev("+getComputedStyle(document.getElementById('jy-front-stomach')).opacity") > 0.3)
    check("ripples spread from the pill", ev("[...document.querySelectorAll('#jy-ripples ellipse')].some(e => +e.getAttribute('rx') > 60 && +e.style.opacity > 0)"))
    caps = titles("stomach", (0.05, 0.3, 0.65, 0.85, 0.97))
    check("chapter 2 captions change in order as you scroll", caps == ev("JOURNEY.stomach.map(c => c.title)"), caps)
    check("the coating note shows under 'The shell gives way'", ev("(jyGoto('stomach', .65), new Promise(r => setTimeout(() => r(document.querySelector('.jy-fine').textContent), 500)))") == ev("JOURNEY.stomach[2].note"))
    at("stomach", 1)
    check("the shell has dissolved", ev("+document.querySelector('.jy-actor .jy-shell').style.opacity") == 0 and ev("+document.querySelector('.jy-actor .jy-edge').style.opacity") == 0)
    hero = "(() => { const r = document.querySelector('.jy-actor .jy-hero').getBoundingClientRect(); return [Math.round(r.left + r.width / 2 - innerWidth / 2), Math.round(r.top + r.height / 2 - innerHeight / 2)] })()"
    hc = ev(hero)
    check("the hero granule is now centred on screen", abs(hc[0]) <= 3 and abs(hc[1]) <= 3, hc)
    check("the hero ring is showing", ev("+document.querySelector('.jy-actor .jy-ring').style.opacity") == 1)
    spread = ev("(() => { const h = document.querySelector('.jy-actor .jy-hero').getBoundingClientRect(); return [...document.querySelectorAll('.jy-actor .jy-g:not(.jy-hero)')].map(g => { const r = g.getBoundingClientRect(); return Math.hypot(r.x - h.x, r.y - h.y) }) })()")
    check("the other granules form a cloud around it, on screen", min(spread) > 20 and max(spread) < 420, [round(min(spread)), round(max(spread))])
    check("the hero is bigger than at the start (camera zoomed in)", ev("document.querySelector('.jy-actor .jy-hero').getBoundingClientRect().width") > 25)
    print("Chapter 3, Small intestine:")
    caps = titles("intestine", (0.05, 0.4, 0.5, 0.75, 0.95))
    check("chapter 3 captions change in order", caps == ev("JOURNEY.intestine.map(c => c.title)"), caps)
    at("intestine", 0.2)
    check("going through the pylorus, the ring opens around the hero", ev("(() => { const y = JY_PYL.y; return jyPylHalf(y, y) - jyPylHalf(y, y - 800) })()") > 30)
    at("intestine", 0.15)
    xs = ev("[...document.querySelectorAll('.jy-actor .jy-g:not(.jy-hero)')].map(g => { const r = g.getBoundingClientRect(); return r.x + r.width / 2 - innerWidth / 2 })")
    check("the other granules squeeze into a column to fit through the ring", max(abs(x) for x in xs) < 90, round(max(abs(x) for x in xs)))
    inside = """(() => { const m = document.getElementById('jy-intestine').style.transform.match(/scale\\(([\\d.]+)\\) translate\\((-?[\\d.]+)px, (-?[\\d.]+)px\\)/);
      const sk = +m[1], hx = -m[2], hy = -m[3], cx = innerWidth / 2, cy = innerHeight / 2;
      return [...document.querySelectorAll('.jy-actor .jy-g:not(.jy-hero)')].filter(g => +g.style.opacity > 0.03).every(g => {
        const r = g.getBoundingClientRect(), wx = hx + (r.x + r.width / 2 - cx) / sk, wy = hy + (r.y + r.height / 2 - cy) / sk;
        return Math.abs(wx - 500) + r.width / 2 / sk <= jyPylHalf(wy, hy) + 1 }) })()"""
    why = inside.replace(".every(g => {", ".map(g => {").replace("return Math.abs(wx - 500) + r.width / 2 / sk <= jyPylHalf(wy, hy) + 1 })", "return [Math.round(wy), Math.round(Math.abs(wx - 500) + r.width / 2 / sk), Math.round(jyPylHalf(wy, hy)), g.style.opacity] }).filter(a => a[1] > a[2] + 1)")
    bad = [q for q in (0.08, 0.15, 0.2, 0.24, 0.28, 0.32) if (at("intestine", q) or True) and not ev(inside)]
    check("granules stay in the fluid, never on the pylorus walls", not bad, bad)
    if bad: at("intestine", bad[0]); print("     outside the fluid [world y, reach, channel half-width, opacity]:", ev(why))
    at("intestine", 0.28)
    check("past the ring they rush outward and fade", ev("[...document.querySelectorAll('.jy-actor .jy-g:not(.jy-hero)')].every(g => +g.style.opacity < 0.5)"))
    at("intestine", 0.48)
    check("the hero granule is dissolving into molecules", float(ev("document.querySelector('.jy-actor .jy-hero').getAttribute('r')")) < 5 and ev("+document.querySelector('.jy-actor .jy-mols').style.opacity") > 0.3)
    check("the other granules are gone", ev("[...document.querySelectorAll('.jy-actor .jy-g:not(.jy-hero)')].every(g => +g.style.opacity === 0)"))
    check("'Not to scale' shows", ev("+getComputedStyle(document.querySelector('.jy-scale')).opacity") == 1)
    at("intestine", 0.72)
    check("the lining cell lights up as the hero crosses it", ev("parseFloat(document.getElementById('jy-int-cell').getAttribute('fill').split(',')[3])") > 0.3)
    hc = ev(hero)
    check("the hero stays centred", abs(hc[0]) <= 3 and abs(hc[1]) <= 3, hc)

    print("Chapter 4, Different paths:")
    caps = titles("paths", (0.05, 0.2, 0.38, 0.52, 0.7, 0.85, 0.97))
    check("chapter 4 captions change in order", caps == ev("JOURNEY.paths.map(c => c.title)"), caps)
    for qq in (0.05, 0.3, 0.55, 0.75, 0.9):
        at("paths", qq); hc = ev(hero)
        if not (abs(hc[0]) <= 3 and abs(hc[1]) <= 3 and ev("+getComputedStyle(document.querySelector('.jy-actor')).opacity") > 0.95): break
    check("the hero stays visible and centred through the whole map", abs(hc[0]) <= 3 and abs(hc[1]) <= 3, [qq, hc])
    vis = lambda k: float(ev(f"document.getElementById('jy-dp-s-{k}').style.getPropertyValue('--on') || 0"))
    route = lambda k: float(ev(f"document.getElementById('jy-dp-r-{k}').getAttribute('opacity')"))
    at("paths", 0.05)
    check("no station labels before a group travels", all(vis(k) == 0 for k in ("large", "liver", "kidney", "bladder")))
    at("paths", 0.2)
    check("stool beat: Large intestine station and track light up, others dark", vis("large") == 1 and route("stool") == 1 and vis("kidney") == 0 and route("kidney") == 0)
    at("paths", 0.415)
    check("liver beat: label shows, stool label gone, liver glows amber", vis("liver") == 1 and vis("large") == 0 and float(ev("document.getElementById('jy-dp-s-liver').style.getPropertyValue('--amber')")) > 0.5)
    at("paths", 0.70)
    check("kidney beat: Kidneys station and track light up; earlier tracks dimmed", vis("kidney") == 1 and route("kidney") == 1 and route("stool") < 0.5)
    at("paths", 0.87)
    left = ev("[...document.querySelectorAll('#jy-dp-dots circle')].filter(c => +c.getAttribute('opacity') > 0.5).length")
    G = ev("JOURNEY.pathsChoreo.groups")
    check("stool and kidney groups have left; the rest remain", left == 11 - G["stool"] - G["kidney"], left)
    check("liver group turned amber", ev("document.querySelectorAll('#jy-dp-dots circle.amber').length") == G["liver"])
    check("no number tallies on screen", not ev("/\\d+ ·/.test(document.getElementById('jy-paths').textContent)"))
    at("paths", 1)
    check("the dive ends in a red flood", float(ev("document.getElementById('jy-paths-tint').style.opacity")) > 0.95)

    print("Chapter 5, Bloodstream:")
    caps = titles("blood", (0.1, 0.4, 0.7, 0.95))
    check("chapter 5 captions change in order", caps == ev("JOURNEY.blood.map(c => c.title)"), caps)
    for qq in (0.1, 0.5, 0.9):
        at("blood", qq); hc = ev(hero)
        if not (abs(hc[0]) <= 3 and abs(hc[1]) <= 3): break
    check("the hero stays centred in the bloodstream", abs(hc[0]) <= 3 and abs(hc[1]) <= 3, [qq, hc])
    at("blood", 0.4)
    check("red cells drift past; no brain blue yet", ev("document.querySelectorAll('.jy-bl-cell').length") == 18 and float(ev("document.getElementById('jy-bl-brain').getAttribute('opacity')")) == 0)
    at("blood", 0.95)
    check("in the capillary: single file, brain blue beyond the wall", ev("[...document.querySelectorAll('.jy-bl-cell')].filter(g => +g.getAttribute('opacity') > 0.5).length") <= 5 and float(ev("document.getElementById('jy-bl-brain').getAttribute('opacity')")) > 0.9)

    print("Chapter 6, Blood-brain barrier:")
    caps = titles("barrier", (0.05, 0.13, 0.35, 0.45, 0.54, 0.63, 0.74, 0.86, 0.97))
    check("chapter 6 captions change in order", caps == ev("JOURNEY.barrier.map(c => c.title)"), caps)
    for qq in (0.05, 0.16, 0.35, 0.6, 0.75, 0.84, 0.95):
        at("barrier", qq); hc = ev(hero)
        if not (abs(hc[0]) <= 3 and abs(hc[1]) <= 3): break
    check("the hero stays centred through the barrier", abs(hc[0]) <= 3 and abs(hc[1]) <= 3, [qq, hc])
    at("barrier", 0.06)
    check("opens on brain tissue (capillaries and neurons), wall not yet shown", float(ev("document.getElementById('jy-bb-net').getAttribute('opacity')")) > 0.95 and float(ev("document.getElementById('jy-bb-wall').getAttribute('opacity')")) < 0.05)
    at("barrier", 0.16)
    check("pulls back to the whole brain, with a ring on the hero's spot", float(ev("document.getElementById('jy-bb-whole').getAttribute('opacity')")) > 0.95 and float(ev("document.getElementById('jy-bb-mark').getAttribute('opacity')")) > 0.9)
    at("barrier", 0.37)
    check("wall view: tight junctions glow, labels show", float(ev("getComputedStyle(document.getElementById('jy-bb-wall')).getPropertyValue('--tj')")) > 0.9 and float(ev("document.getElementById('jy-bb-t-tj').getAttribute('opacity')")) > 0.9)
    hy = lambda: ev("+document.getElementById('jy-bb-wall').getAttribute('transform').match(/translate\\(([-\\d.]+) ([-\\d.]+)\\)$/)[2]")
    check("hero is on the blood side before crossing", -hy() < 0)
    lobe = "+document.querySelector('#jy-bb-d1 rect').getAttribute('transform').match(/rotate\\(([-\\d.]+)/)[1]"
    at("barrier", 0.70); rest = ev(lobe)
    at("barrier", ev("jyBbPlan(JOURNEY.barrierChoreo).door1[3] + 0.019")); flip = ev(lobe)
    check("the blood-side door rocks over while the hero is in it", rest < 0 and flip > 0, [rest, flip])
    at("barrier", ev("jyBbPlan(JOURNEY.barrierChoreo).tops[3] + 0.045"))
    check("the hero is inside the wall cell mid-crossing", 0 < -hy() < 140, -hy())
    at("barrier", 0.37); red = ev("document.getElementById('jy-bb-lumen').getAttribute('fill')")
    at("barrier", 0.97)
    check("on the brain side; red has resolved to blue", -hy() > 140 and ev("document.getElementById('jy-bb-lumen').getAttribute('fill')") == ev("JY_BB_TONES.lumen[1]") and red == ev("JY_BB_TONES.lumen[0]"), [-hy(), red])
    check("chapter 6 dot is current", ev("[...document.querySelectorAll('.jy-rail li')].findIndex(l => l.hasAttribute('aria-current'))") == 5)

    print("Chapter 7, Synapse:")
    C7 = ev("JOURNEY.synapseChoreo")
    caps = titles("synapse", [c + 0.01 for c in ev("JOURNEY.synapse.map(c => c.at)")])
    check("chapter 7 captions change in order", caps == ev("JOURNEY.synapse.map(c => c.title)"), caps)
    for qq in (0.04, 0.15, 0.3, 0.4, 0.5, C7["fire"][0] + 0.02):
        at("synapse", qq); hc = ev(hero)
        if not (abs(hc[0]) <= 3 and abs(hc[1]) <= 3): break
    check("our molecule stays centred until the handover", abs(hc[0]) <= 3 and abs(hc[1]) <= 3, [qq, hc])
    plan = "jySyPlan(JOURNEY.synapseChoreo)"
    at("synapse", ev(plan + ".doors.entry[0] + 0.019"))
    check("taken up into the neuron through a carrier (door rocks)", ev("+document.querySelector('#jy-sy-de rect').getAttribute('transform').match(/rotate\\(([-\\d.]+)/)[1]") > 0)
    at("synapse", C7["assemble"][0] + 0.03)
    check("our molecule is tagged Precursor", float(ev("document.getElementById('jy-sy-t-precursor').getAttribute('opacity')")) > 0.95 and float(ev("document.getElementById('jy-sy-t-made').getAttribute('opacity')")) < 0.05)
    check("both helpers are labelled Cofactor", ev("[...document.querySelectorAll('.jy-sy-chip text')].map(t => t.textContent)") == ["Cofactor", "Cofactor"])
    at("synapse", C7["pack"][0] + 0.02)
    check("after the second enzyme it's a neurotransmitter (amber halo, tag switches)", float(ev("document.getElementById('jy-sy-halo').getAttribute('opacity')")) > 0.95 and float(ev("document.getElementById('jy-sy-t-made').getAttribute('opacity')")) > 0.95)
    at("synapse", C7["spark"][0] + 0.012)
    check("spark runs down the axon; caption moves right on wide screens", float(ev("document.getElementById('jy-sy-spark').getAttribute('opacity')")) > 0.9 and ev("document.getElementById('jy').classList.contains('jy-capright')"))
    at("synapse", C7["spark"][1])
    check("the two fronts meet at the vesicle with a flash", float(ev("document.getElementById('jy-sy-flash').getAttribute('opacity')")) > 0.5)
    at("synapse", C7["release"][1])
    check("vesicle has fused and released", float(ev("document.getElementById('jy-sy-hvc').getAttribute('opacity')")) < 0.05)
    at("synapse", C7["fire"][0] + 0.02)
    check("receptors light up", float(ev("document.querySelector('.jy-sy-rglow[data-i=\"3\"]').getAttribute('opacity')")) > 0.8)
    at("synapse", C7["pass"][0] + 0.005)
    check("handover step 1 (camera still): our molecule swaps to a copy in the scene at the same spot, no ghost", ev(hero) is not None and float(ev("document.getElementById('jy-sy-mol').getAttribute('opacity')")) > 0.4 and ev("(() => { const m = document.getElementById('jy-sy-mol').getBoundingClientRect(); return Math.hypot(m.x + m.width / 2 - innerWidth / 2, m.y + m.height / 2 - innerHeight / 2) < 4 })()"))
    at("synapse", C7["pass"][1] + 0.01)
    sig_c = "(() => { const r = document.querySelector('#jy-sy-sig circle:last-child').getBoundingClientRect(); return [Math.round(r.x + r.width / 2 - innerWidth / 2), Math.round(r.y + r.height / 2 - innerHeight / 2)] })()"
    check("handover step 2: the camera is on the signal, still waiting at the receptors", [abs(v) <= 3 for v in ev(sig_c)] == [True, True], ev(sig_c))
    check("handover: the camera follows the signal; our molecule fades into the scene", float(ev("document.querySelector('.jy-actor').style.opacity || 1")) < 0.05 and float(ev("document.getElementById('jy-sy-sig').getAttribute('opacity')")) > 0.9)
    check("the clearing still plays: our molecule is taken back up", float(ev("document.getElementById('jy-sy-mol').getAttribute('opacity')")) == 1 and ev("+document.querySelector('#jy-sy-du rect').getAttribute('transform').match(/rotate\\(([-\\d.]+)/)[1]") > -14)
    at("synapse", (C7["axon"][0] + C7["axon"][1]) / 2)
    check("part way down the next axon: its rim lights behind the signal", min(float(e) for e in ev("[...document.querySelectorAll('#jy-sy-rim2 .jy-sy-rimt')].map(p => parseFloat(p.style.strokeDasharray))")) > 0.1)
    check("no calls to action yet", not ev("document.getElementById('jy').classList.contains('jy-done')"))
    at("synapse", C7["launch"][0] + 0.01)
    check("the signal launches: camera stops, signal pulls ahead", ev(sig_c)[0] > 5)
    at("synapse", 1)
    check("the axon sits above the last caption", ev("(() => { const a = document.querySelector('#jy-sy-rim2 .jy-sy-rimt').getBoundingClientRect(), c = document.querySelector('.jy-t').getBoundingClientRect(); return a.bottom < c.top })()"))
    check("the end: calls to action show, reachable by keyboard", ev("document.getElementById('jy').classList.contains('jy-done')") and ev("getComputedStyle(document.getElementById('jy-cta')).visibility") == "visible" and ev("[...document.querySelectorAll('.jy-cta button')].every(b => b.tabIndex === 0)"))
    check("CTA wording from content/journey.js", ev("[...document.querySelectorAll('.jy-cta button')].map(b => b.textContent)") == ev("[JOURNEY.cta.explore, JOURNEY.cta.stack, JOURNEY.cta.replay]"))
    check("chapter 7 dot is current", ev("[...document.querySelectorAll('.jy-rail li')].findIndex(l => l.hasAttribute('aria-current'))") == 6)
    ev("document.querySelector('.jy-cta [data-journey=explore]').click()"); time.sleep(.8)
    check("Meet your neurotransmitters opens Explore", ev("location.hash") in ("", "#") and ev("!!document.querySelector('.tc')"))
    open_journey(); ev("document.querySelector('[data-journey=start]').click()"); time.sleep(2.5)

    at("swallow", 0.5)
    check("scrolling back up rebuilds the capsule", ev("+document.querySelector('.jy-actor .jy-shell').style.opacity") == 1 and ev("document.querySelectorAll('.jy-actor .jy-g[transform]').length") == 0 and ev(centre) == [0, 0])
    ev("document.querySelector('.jy-skiptour').click()"); time.sleep(.5)
    check("Skip journey link opens the Stack builder mid-tour", ev("location.hash") == "#stack" and ev("scrollY") == 0)
    open_journey()
    check("coming back starts fresh at the two pills", ev("document.querySelectorAll('.jy-pill:not(.jy-actor)').length") == 2 and ev("document.documentElement.scrollHeight <= innerHeight + 2"))

    print("Phone width:")
    size(375, 812, True); open_journey()
    check("pills stack vertically", ev("(() => { const [a, b] = [...document.querySelectorAll('.jy-pill')].map(x => x.getBoundingClientRect()); return b.top > a.bottom })()"))
    check("no sideways scroll", ev("document.documentElement.scrollWidth <= innerWidth"))
    size(1280, 800)

    print("Reduced motion:")
    c.call("Emulation.setEmulatedMedia", features=[{"name": "prefers-reduced-motion", "value": "reduce"}])
    open_journey()
    check("no float or entrance animation", ev("[...document.querySelectorAll('.jy-pill')].every(b => getComputedStyle(b).animationName === 'none')"))
    ev("document.querySelector('[data-journey=start]').click()"); time.sleep(.3)
    check("Start jumps straight to the scene, no flight", ev("document.getElementById('jy').classList.contains('jy-inscene')"))
    ev("scrollTo(0, .1 * (document.documentElement.scrollHeight - innerHeight))"); time.sleep(.4)
    check("no zoom: the head holds one scale", ev("Math.abs(innerWidth / document.getElementById('jy-mouth').viewBox.baseVal.width - JOURNEY.swallowChoreo.headScale[0] * Math.min(1.3, Math.max(.7, innerHeight / 820))) < 1e-2"))
    c.call("Emulation.setEmulatedMedia", features=[])

    check("no page errors", ev("__e.length") == 0, ev("__e"))
finally:
    proc.terminate()
print(f"\n{'All passed' if not fails else str(len(fails)) + ' failed: ' + ', '.join(fails)}")
sys.exit(1 if fails else 0)
